name: Deployment to itch.io

on:
  # workflow_dispatch will enable manual triggers
  workflow_dispatch:
  pull_request:
  push:
    tags: [ "*.*.*" ]
  

env:
  CARGO_TERM_COLOR: always
  PROJECT_NAME: pipes-rs

jobs:
  deploy-wasm-linux-windows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          # -L follows redirects
          # -O specifies output name
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          # GNU unzip tends to not set the executable bit even though it's set in the .zip
          chmod +x butler
          # just a sanity check run (and also helpful in case you're sharing CI logs)
          ./butler -V

      - name: Build
        run: cargo build -r

      - name: Run tests
        run: cargo test -r

      - name: Package Linux
        run: |
          mkdir -p ${PROJECT_NAME}_linux
          cp target/release/${PROJECT_NAME} ${PROJECT_NAME}_linux/
          zip -FS -r ${PROJECT_NAME}_linux.zip ${PROJECT_NAME}_linux/*
          sha512sum ${PROJECT_NAME}_linux.zip

      - name: Deploy Linux to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: ./butler push ${PROJECT_NAME}_linux.zip jmmut/pipes:linux

      - name: Compile and package WebAssembly
        run: |
          cargo install wasm-pack
          ./recompile_web.sh
          zip -FS -r wasm.zip built_html/*
          sha512sum wasm.zip

      - name: Deploy WebAssembly to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: ./butler push wasm.zip jmmut/pipes:html5

###### For some reason the windows build fails:
  #  rustup target add x86_64-pc-windows-gnu
  #  Compiling pipes-rs v0.1.0 (/home/runner/work/pipes-rs/pipes-rs)
  # error: linker `x86_64-w64-mingw32-gcc` not found
  #  |
  #  = note: No such file or directory (os error 2)
#      - name: Compile and package Windows
#        run: |
#          rustup target add x86_64-pc-windows-gnu
#          cargo build -r --target x86_64-pc-windows-gnu
#          mkdir -p ${PROJECT_NAME}_windows
#          cp target/x86_64-pc-windows-gnu/release/${PROJECT_NAME}.exe ${PROJECT_NAME}_windows/
#          zip -FS -r ${PROJECT_NAME}_windows.zip ${PROJECT_NAME}_windows/*
#          sha512sum ${PROJECT_NAME}_windows.zip
#
#      - name: Deploy Windows to itch.io
#        env:
#          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
#        run: ./butler push ${PROJECT_NAME}_windows.zip jmmut/pipes:windows

  deploy-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          # -L follows redirects
          # -O specifies output name
          curl -L -o butler.zip https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default
          unzip butler.zip
          # GNU unzip tends to not set the executable bit even though it's set in the .zip
          chmod +x butler
          # just a sanity check run (and also helpful in case you're sharing CI logs)
          ./butler -V

      - name: Build
        run: cargo build -r

      - name: Run tests
        run: cargo test -r

      - name: Package Mac
        run: |
          mkdir -p ${PROJECT_NAME}_mac
          cp target/release/${PROJECT_NAME} ${PROJECT_NAME}_mac/
          zip -FS -r ${PROJECT_NAME}_mac.zip ${PROJECT_NAME}_mac/*
          # sha512sum ${PROJECT_NAME}_mac.zip # error: sha512sum doesn't exist in mac. TODO: Find alternative.

      - name: Deploy Mac to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: ./butler push ${PROJECT_NAME}_mac.zip jmmut/pipes:mac
